const datas = [
  {
    id: 1,
    name: "Odis Rhinehart",
    level: "Warga",
    favorite: "Chicken & Ribs Combo",
    transaction: 194700,
  },
  {
    id: 2,
    name: "Kris Roher",
    level: "Warga",
    favorite: "Chicken & Ribs Combo",
    transaction: 194700,
  },
  {
    id: 3,
    name: "Serenity Fisher",
    level: "Juragan",
    favorite: "Chicken & Ribs Combo",
    transaction: 194700,
  },
  {
    id: 4,
    name: "Brooklyn Warren",
    level: "Sultan",
    favorite: "Chicken & Ribs Combo",
    transaction: 194700,
  },
  {
    id: 5,
    name: "Franco Delort",
    level: "Juragan",
    favorite: "Chicken & Ribs Combo",
    transaction: 194700,
  },
  {
    id: 6,
    name: "Saul Geoghegan",
    level: "Juragan",
    favorite: "Chicken & Ribs Combo",
    transaction: 194700,
  },
  {
    id: 7,
    name: "Alfredo Vetrovs",
    level: "Juragan",
    favorite: "Chicken & Ribs Combo",
    transaction: 194700,
  },
  {
    id: 8,
    name: "Cristofer Vetrovs",
    level: "Konglomerat",
    favorite: "Chicken & Ribs Combo",
    transaction: 194700,
  },
  {
    id: 9,
    name: "Calvin Steward",
    level: "Konglomerat",
    favorite: "Chicken & Ribs Combo",
    transaction: 194700,
  },
  {
    id: 10,
    name: "Calvin Steward",
    level: "Konglomerat",
    favorite: "Chicken & Ribs Combo",
    transaction: 194700,
  },
  {
    id: 11,
    name: "Odis Rhinehart",
    level: "Warga",
    favorite: "Chicken & Ribs Combo",
    transaction: 194700,
  },
  {
    id: 12,
    name: "Kris Roher",
    level: "Warga",
    favorite: "Chicken & Ribs Combo",
    transaction: 194700,
  },
  {
    id: 13,
    name: "Serenity Fisher",
    level: "Juragan",
    favorite: "Chicken & Ribs Combo",
    transaction: 194700,
  },
  {
    id: 14,
    name: "Brooklyn Warren",
    level: "Sultan",
    favorite: "Chicken & Ribs Combo",
    transaction: 194700,
  },
  {
    id: 15,
    name: "Franco Delort",
    level: "Juragan",
    favorite: "Chicken & Ribs Combo",
    transaction: 194700,
  },
  {
    id: 16,
    name: "Saul Geoghegan",
    level: "Juragan",
    favorite: "Chicken & Ribs Combo",
    transaction: 194700,
  },
  {
    id: 17,
    name: "Alfredo Vetrovs",
    level: "Juragan",
    favorite: "Chicken & Ribs Combo",
    transaction: 194700,
  },
  {
    id: 18,
    name: "Cristofer Vetrovs",
    level: "Konglomerat",
    favorite: "Chicken & Ribs Combo",
    transaction: 194700,
  },
  {
    id: 19,
    name: "Calvin Steward",
    level: "Konglomerat",
    favorite: "Chicken & Ribs Combo",
    transaction: 194700,
  },
  {
    id: 20,
    name: "Calvin Steward",
    level: "Konglomerat",
    favorite: "Chicken & Ribs Combo",
    transaction: 194700,
  },
  {
    id: 21,
    name: "Odis Rhinehart",
    level: "Warga",
    favorite: "Chicken & Ribs Combo",
    transaction: 194700,
  },
  {
    id: 22,
    name: "Kris Roher",
    level: "Warga",
    favorite: "Chicken & Ribs Combo",
    transaction: 194700,
  },
  {
    id: 23,
    name: "Serenity Fisher",
    level: "Juragan",
    favorite: "Chicken & Ribs Combo",
    transaction: 194700,
  },
  {
    id: 24,
    name: "Brooklyn Warren",
    level: "Sultan",
    favorite: "Chicken & Ribs Combo",
    transaction: 194700,
  },
  {
    id: 25,
    name: "Franco Delort",
    level: "Juragan",
    favorite: "Chicken & Ribs Combo",
    transaction: 194700,
  },
  {
    id: 26,
    name: "Saul Geoghegan",
    level: "Juragan",
    favorite: "Chicken & Ribs Combo",
    transaction: 194700,
  },
  {
    id: 27,
    name: "Alfredo Vetrovs",
    level: "Juragan",
    favorite: "Chicken & Ribs Combo",
    transaction: 194700,
  },
  {
    id: 28,
    name: "Cristofer Vetrovs",
    level: "Konglomerat",
    favorite: "Chicken & Ribs Combo",
    transaction: 194700,
  },
  {
    id: 29,
    name: "Calvin Steward",
    level: "Konglomerat",
    favorite: "Chicken & Ribs Combo",
    transaction: 194700,
  },
  {
    id: 30,
    name: "Calvin Steward",
    level: "Konglomerat",
    favorite: "Chicken & Ribs Combo",
    transaction: 194700,
  },
];

export const getDataCustomers = () => {
  return datas;
};
